name: hello
on:
- push
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo hello world
      - run: whoami
      - run: pwd
      - run: ls
      - run: cat /etc/os-release
      - run: env
      - run: docker version
      - run: docker build -t foo .
      - run: docker run --rm --name foo -d -p 8080:8080 -e PORT=8080 foo
      - run: curl localhost:8080
      - run: docker stop foo
