name: hello
on:
- push
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo hello world
      - run: whoami
      - run: pwd
      - run: ls
      - run: cat /etc/os-release
      - run: env
      - run: docker version
